### ISSUE TITLE
More products tab is not showing products at all

### ISSUE THREAD

**Issue by Mashenka** [UsabilityDynamics/lib-wp-bootstrap#11]
![image](https://user-images.githubusercontent.com/5111163/47316867-cffd1e80-d650-11e8-9c4e-d4bfc779ba16.png)

**Comment by alimuzzaman** [comment]
@Mashenka 
Which version and where did you find the problem?

**Comment by Mashenka** [comment]
@alimuzzaman I'm checking here - https://udx-ci-develop-maria.rabbit.ci/wp-admin/edit.php?post_type=property&page=wp-property%2Fwp-property_wp-propertyadd-onsmanager&screen=more_products

**Comment by Mashenka** [comment]
@alimuzzaman 
ok, to see our products users should have our api.usabilitydynamics.com in white host list?
can we show then message about that instead of there is no any product

**Comment by alimuzzaman** [comment]
@Mashenka Yes, it can be done.

**Comment by Mashenka** [comment]
ok, lets mention that to see available WP-Property products they need to add our domain to the whitelist and point them where to do that
