### ISSUE TITLE
Udate Notices with correct links and info

### ISSUE THREAD

**Issue by Mashenka** [UsabilityDynamics/lib-wp-bootstrap#9]
![image](https://user-images.githubusercontent.com/5111163/46014662-b790f700-c0d8-11e8-9a07-bcb5d72d0a2c.png)

Thank you for using Usability Dynamics plugin {name-of the plugin}. 

Plugin's docs - github.io page
Post your idea - remove that link
Support - Product/Settings page - Support tab

@andypotanin do you have a suggestion where that welcome message should direct users else?

**Comment by andypotanin** [comment]
@Mashenka no. we need to disable all update/license related nags.

**Comment by Mashenka** [comment]
@andypotanin that one is welcome message of core plugin when you install or update core plugin

**Comment by andypotanin** [comment]
@Mashenka I know, I want us to only have the Getting Started / Welcome page that we show, and then no nags after that.

**Comment by SoSeductive** [comment]
@Mashenka Template for notice removed. You can check here - https://udx-ci-develop-den.rabbit.ci/wp-admin

PR if all is OK - https://github.com/UsabilityDynamics/lib-wp-bootstrap/pull/10

**Comment by andypotanin** [comment]
@SoSeductive I see: 
![image](https://user-images.githubusercontent.com/1255935/46225062-2020e380-c326-11e8-97b5-67eefddd6794.png)

What should I be seeing?

**Comment by andypotanin** [comment]
@SoSeductive I see, you removed the one notice, can you hide the others?

**Comment by Mashenka** [comment]
@andypotanin Notices about the license we need, because users won't get updates if license not set up

**Comment by andypotanin** [comment]
Okay, thank you, looks good.
